### ISSUE TITLE
PubMed keyword detection: use MeSH as reference list

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#103]
Currently, when an article does not have any keywords, we use the 10 most frequent words as input for the labelling procedure. It may be much more useful to use controlled vocabulary from the [Medical Subject Headings](https://www.nlm.nih.gov/mesh/) for keyword detection.

**Comment by pkraker** [comment]
One welcome effect would be that keywords such as 2015february (see e.g. this [zika map](http://openknowledgemaps.org/vis.php?id=6bdd0ec5f60beb8b07de89d472efc5fa&query=zika&service=pubmed)) would vanish.

**Comment by pkraker** [comment]
Could also be interesting to couple this approach with a more sophisticated keyphrase extraction algorithm. This is a nice intro to the subject: http://bdewilde.github.io/blog/2014/09/23/intro-to-automatic-keyphrase-extraction/

**Comment by chreman** [comment]
Sounds interesting. I think we'll have to remain with unsupervised algorithms, but a combination of better features (e.g. filtered for nouns, noun n-grams, MeSH headings) and a graph-based or topic-based algorithm could be promising.
Only problem is evaluation, we currently have no gold-standard to compare against, and would need to come up with a measure here, or have a round of qualitative evaluation after implementation for finetuning.

**Comment by pkraker** [comment]
+1 on the unsupervised algorithms. Regarding evaluation, I would suggest using primarily qualitative evaluation for now. My assumption is that any approach using controlled vocabulary, excluding items with empty abstracts and involving an unsupervised algorithms more sophisticated than the naive approach implemented now will improve the overall quality of the labels. A simple measure to choose between algorithms could be to test for the number of multi-grams in the top n of the result set, as they seem to indicate higher quality keyphrases.

**Comment by chreman** [comment]
OK, sounds like a way forward.

**Comment by Bubblbu** [comment]
+1 that we can probably improve the labeling with a few basic changes (e.g. moving to more sophisticated keyword extraction). One thing that I was pondering:

+ *Quantitative Evaluation*
    I think it could be interesting to introduce a quantitative measure for the naming quality based on the distribution of the tf-idf scores. Currently we are taking the top-n terms in the tf-idf scores. But what if the distribution of scores is uniform? Checking the uniformity could at least give us a quantitative measure of the quality of the acquired labels.

This would at least give us the possibility to evaluate the tf-idf labels of a bubble. Which I think is important, as we will still run into cases where the available ontologies/dictionaries are simply not applicable to the map. Which would again require an alternative labeling routine and some sort of evaluation.

**Comment by pkraker** [comment]
I did a spot-check of tf-idf scores when I first introduced the algorithm, but the difference between tf-idf and top n was so obvious that I stopped. But  I agree, it might be useful to compare various extraction algorithms!

**Comment by tanteuschi** [comment]
closing this in favour of #60
