### ISSUE TITLE
Nonsensical labels

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#104]
There are still a fair amount of nonsensical labels in maps. A good example is the [DOAJ map on open science](http://openknowledgemaps.org/vis.php?id=c7bd63273a9032d8f05d8d1f54787c10&query=open%20science&service=doaj#). The bubble in the lower right corner is all about open source. Instead, the labels are "ArcGIS, CS2013, GRASS GIS". On the top, there are two bubbles, which have "20government" as a label, but do not include research on policy issues. In these two cases, the problem may be further aggravated the limited availability of abstracts (see #101).

**Comment by Bubblbu** [comment]
Related to #105 and #101
