### ISSUE TITLE
Move labelling from PHP to R

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#105]
The current implementation of the TF-IDF labelling algorithm in PHP works OK, but has its problems (see e.g. #95). It would be beneficial to include labelling in the R part, which would have the added benefit of all analysis tasks in one place and the possible inclusion in the evaluation environment.

**Comment by Bubblbu** [comment]
@chreman started implementation in PR #110

**Comment by Bubblbu** [comment]
Related PR #114
