### ISSUE TITLE
rbace updates

### ISSUE THREAD

**Issue by sckott** [OpenKnowledgeMaps/Headstart#118]
been updating `rbace` - current version on master:

- now has fxns for the two other routes on their API, repositories and profiles. 
- added facet params and output to `bs_search()`
- output of `bs_search()` is now a list to accommodate optional facet output, so just need to change to `x$docs` to get to the same data.frame as before
- `boost` param in `bs_search` is now `boost_oa` and is a logical not a character input

**Comment by pkraker** [comment]
New `rbace` version has now been integrated in Headstart.

**Comment by sckott** [comment]
thanks
