### ISSUE TITLE
PubMed search returns fewer papers than on PubMed itself

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#124]
Example:
https://openknowledgemaps.org/vis.php?id=2c0ac8e35d26f6b6587316bf7ebed0b3&query=altmetrics&service=pubmed (38 results)
vs.
https://www.ncbi.nlm.nih.gov/pubmed/?term=altmetrics (55 results)

I assume that this is due to the fact that we pass the search params explicitely (i.e. we explicitely specify all document types instead of just leaving the parameter out).

**Comment by sckott** [comment]
this https://www.ncbi.nlm.nih.gov/pubmed/?cmd=HistorySearch&querykey=3 gives an error, though searching _altmetrics_ on pumbed i get 55 results, does that sound right?

**Comment by pkraker** [comment]
Sorry, I used the history function which only works for a user. Replaced the link with the working one above: https://www.ncbi.nlm.nih.gov/pubmed/?term=altmetrics

**Comment by pkraker** [comment]
And yep, PubMed returns 55 results, whereas OKMaps reports 38 results.

**Comment by pkraker** [comment]
Updated the publication types in OpenKnowledgeMaps/project-website. Part of the discrepancy is explained by the fact that we only take items with an abstract.

**Comment by sckott** [comment]
@pkraker since you closed this, does that means its working now?

**Comment by pkraker** [comment]
@sckott yes, it's been fixed.
