### ISSUE TITLE
Proposal for solving the BASE de-duplication issue

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#126]
A major issue with BASE integration is that there are duplicated entries, which create perfect similarity among several items and thereby distort the maps and confuse users.

So far, we have always considered this to be a too complex problem to solve when computing maps on the fly. Looking deeper into the problem, I have made two observations that - if true on the large scale - would turn it into a much more manageable problem:
1. Duplicated entries are almost always subsequent items in the result list, or 1 item apart.
1. There are usually only a few articles with duplicated entries
1. The title is almost always identical

Therefore, I suggest the following procedure:
* We request a few more items from BASE on every call, say 120
* Going through the list, for every item, we compare titles of items immediately after or 1 position apart. we use a Levenshtein ratio as described in [this paper](http://www.know-center.tugraz.at/download_extern/papers/DLvsRSvsCites_schloegl_etal.pdf) (page 3 at the bottom).
* When encountering a duplicate item, we keep the one that is OA, or if both or none are OA, the item with more metadata fields.

**Comment by pkraker** [comment]
I have created a working implementation for the proposal. The main remaining problem is that BASE allows to retrieve a maximum of 100 records.

**Comment by joschirr** [comment]
This sounds interesting and promising.
However I wonder about the accuracy of the results if the items are compared only by title:
* I would expect more false positives for short titles

In addition the following criteria (with a proper weighting should be considered)
* PIDs, accession numbers
* the normalized publication date should be considered (it may differ by one or two years, but a difference of 10 or more years may indicate the items do not belong together )
* the normalized publication type
* of course the OA item must be prominent, but all the other instances should not be hidden or dropped.

**Comment by pkraker** [comment]
@joschirr Thanks for your comments. We should definitely make sure that the titles are not too short - e.g. "Editorial". But evidence suggests that esp. journal article titles (our standard setting) are unique.
Thanks for your proposal of merging criteria, we will take them into careful consideration when designing the algorithm.

**Comment by pkraker** [comment]
Via the analysis of @chreman, here's a good example of how duplicate papers can skew a map considerably. 7 of 13 clusters are formed by duplicate entries: https://openknowledgemaps.org/vis.php?id=5d8419e125704ea1fd49e36a38f03055&query=brain&service=base

**Comment by pkraker** [comment]
Related: #74

**Comment by pkraker** [comment]
The amazing people at BASE have now increased the limit to 125 👍

**Comment by pkraker** [comment]
With the help of @chreman, the deduplication has been extended to compare all titles within the result set. 

If the title is shorter than 15 characters and/or consists of a single word (no spaces), then the author string is added to the title for comparison. This should prevent that items with the same short name are merged.

In addition, we have introduced the following criteria for deciding which item will be kept (in descending order of importance): item is OA, has longer subject, has longer abstract, has longer author string, has longer source string.
