### ISSUE TITLE
Alternate clicks on papers and list items lead to wrong behaviour of title links

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#146]
Steps to reproduce:

1. Click on list item -> map zooms in
1. Click on bubble -> list resets to items in bubble
1. Click on a different paper in the bubble -> list item is enlarged
1. Click on title -> list resets

The desired behaviour at this point would be to open a new tab with the HTML link of the paper.

**Comment by rbachleitner** [comment]
The core of this issue is: The list titles of enlarged OA papers will open the HTML link, the list title of enlarged non-oa papers will not but will reset the list instead. I will investigate this.

**Comment by pkraker** [comment]
Works now, thanks!
