### ISSUE TITLE
keep links between bubble title and content

### ISSUE THREAD

**Issue by chreman** [OpenKnowledgeMaps/Headstart#152]
* if e.g. a keyword from a paper becomes part of a bubble title and people filter for it, it currently can not be found, since keywords are not displayed in the list
* also, if we change to an algorithm that creates more abstract descriptions of bubbles, it may not be guaranteed that the bubble title still directly corresponds to the papers. this may break with expectations, if e.g. a user searches for a phrase from the bubble title and can not find any paper for that.

**Comment by tanteuschi** [comment]
keywords are now displayed in the list for each item. should there be any other issues, please open a new issue.
