### ISSUE TITLE
Once again: Issues with character encoding

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#156]
Example: search for contemporary art in BASE

Apparently at one point in the backend pipeline Unicode chars fail to be encoded properly and end up as, e.g. "???????".

@pkraker @chreman could you maybe add whatever you've talked about so far or know? I will start to look into the bug in the next few days.

**Comment by pkraker** [comment]
I am pretty sure by now that this happens during the handover from R to PHP. If you dump the R output into a text file, it contains the characters in the form of `<U+0000>`, but if you do the same for the output that it is returned by the exec call, then it already contains the question marks. So the only viable solution, it seems, would be to rewrite the characters in R before returning them. But this seems to be somewhat of a challenge, as detailed here: https://stackoverflow.com/questions/36108790/trouble-with-strings-with-u0092-unicode-characters

**Comment by pkraker** [comment]
@sckott did you encounter this problem before?

**Comment by sckott** [comment]
will have a 🕐

**Comment by sckott** [comment]
What parts of each record are you seeing it in?  Title?  Abstract? Authors? All of those?

**Comment by sckott** [comment]
Would help if someone could paste in the output of `sessionInfo()` so we can see if there's some kind of locale issue

**Comment by sckott** [comment]
I can't replicate the problem locally - so perhaps it's a locale issue , not sure yet

**Comment by pkraker** [comment]
I've seen them in a number of fields. For example, [these are the titles that I get back for the contemporary art query](https://github.com/OpenKnowledgeMaps/Headstart/files/1267824/base_output_titles.txt). The problem is with the characters encoded as `<U+XXXX>`. R seems to be fine with them, but our technologies down the stream (PHP and JavaScript) aren't.

My locale is set to 
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252

**Comment by sckott** [comment]
thanks @pkraker  - but i only see the tibble data.frame, so I can't see the titles that are hidden

**Comment by sckott** [comment]
Trying to follow your eg, here I can find one that has a bunch of errant question marks. 

```r
library(rbace)
x <- bs_search(query = "textus:contemporary textus:art date:[1665-01-06 TO 2017-08-31] typenorm:(121) description:?", hits = 100, verbose=TRUE)
grep("\\?{2,}", x$docs$dctitle, value = TRUE)
#> [1] "??????????? ?????? ?? ????????? ????????? ?????????? ? ????????? ????? ; Utopia?s modifications and the main kinds of utopian consciousness in contemporary world"
```

Trying this request with curl on command line shows that the question marks are already there 

```sh
curl -v -H 'User-Agent: r-curl crul rOpenSci(rbace)' 'http://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi?func=PerformSearch&query=textus%3acontemporary%20textus%3aart%20date%3a%5b1665-01-06%20TO%202017-08-31%5d%20typenorm%3a%28121%29%20description%3a%3f&hits=100'
```

**Comment by pkraker** [comment]
Thanks! @Bubblbu wil take over from here.

**Comment by sckott** [comment]
so looks like we need to get in touch with BASE folks to see if they can fix this on their end

**Comment by Bubblbu** [comment]
@sckott just wondering how you determined that the problem is on the BASE side of things? Haven't had time to look into the issue itself so just trying to stay up-to-date

**Comment by sckott** [comment]
I looked at the data returned from BASE, and the encoding was already messed up in the returned payload from their API, so it's messed up before getting to the R work part

**Comment by sckott** [comment]
@pietsch see https://github.com/OpenKnowledgeMaps/Headstart/issues/156#issuecomment-326411900 above - Seems like there's some encoding issues on BASE's side of things, thoughts?

**Comment by sckott** [comment]
checked again now, ran this example https://github.com/OpenKnowledgeMaps/Headstart/issues/156#issuecomment-326411900 again , and it persists

**Comment by sckott** [comment]
Tested again using https://github.com/OpenKnowledgeMaps/Headstart/issues/156#issuecomment-326411900 code - encoding problem still persists

**Comment by chreman** [comment]
The solution to this issue is out of our control.
