### ISSUE TITLE
Pubmed search results differ from OKMaps

### ISSUE THREAD

**Issue by tanteuschi** [OpenKnowledgeMaps/Headstart#161]
Search results in Pubmed differ from Open Knowledge Maps. Example: **zika review** in Pubmed (sort by: best match) 
![bildschirmfoto 2017-11-08 um 21 15 40](https://user-images.githubusercontent.com/19272712/32572162-11cc0b4e-c4ca-11e7-92e3-ca9bc0d84c0f.png)

first paper of the Pubmed search is not included in the OKMaps overview for **zika review** https://openknowledgemaps.org/map/3bea33a9f9c8f6d5f55655260a9eae9c

Why?

**Comment by Bubblbu** [comment]
I've been working with the PubMed API while someone else was mainly using the web interface. We also had troubles to reproduce identical results... But didn't spend too much time on that, so not sure if the problem was just our inability to reproduce the exact same search query. Maybe @sckott knows more?

What our backend definitely does is add a few search parameters for the min and max publication date (couldn't find our default values for "All time"), and `hasabstract[text]` which you can activate as a filter in the PubMed results, and the publication types (which should be all of them per default I think).

**Comment by sckott** [comment]
having a look

**Comment by sckott** [comment]
Hmm, is there a way to sort out exactly what API request was submitted to Pubmed from a users command in the OKM interface?

**Comment by Bubblbu** [comment]
These are the params sent to pubmed.R in the backend for a user search "zika review"

```
optradio:pubmed
time_range:any-time
sorting:most-relevant
article_types[]:addresses
article_types[]:autobiography
article_types[]:bibliography
article_types[]:biography
article_types[]:book illustrations
article_types[]:case reports
article_types[]:classical article
article_types[]:clinical conference
article_types[]:clinical study
article_types[]:clinical trial
article_types[]:clinical trial, phase i
article_types[]:clinical trial, phase ii
article_types[]:clinical trial, phase iii
article_types[]:clinical trial, phase iv
article_types[]:collected works
article_types[]:comment
article_types[]:comparative study
article_types[]:congresses
article_types[]:consensus development conference
article_types[]:consensus development conference, nih
article_types[]:controlled clinical trial
article_types[]:corrected and republished article
article_types[]:dataset
article_types[]:dictionary
article_types[]:directory
article_types[]:duplicate publication
article_types[]:editorial
article_types[]:electronic supplementary materials
article_types[]:english abstract
article_types[]:ephemera
article_types[]:evaluation studies
article_types[]:festschrift
article_types[]:government publications
article_types[]:guideline
article_types[]:historical article
article_types[]:interactive tutorial
article_types[]:interview
article_types[]:introductory journal article
article_types[]:journal article
article_types[]:lectures
article_types[]:legal cases
article_types[]:legislation
article_types[]:letter
article_types[]:meta analysis
article_types[]:multicenter study
article_types[]:news
article_types[]:newspaper article
article_types[]:observational study
article_types[]:overall
article_types[]:patient education handout
article_types[]:periodical index
article_types[]:personal narratives
article_types[]:pictorial works
article_types[]:popular works
article_types[]:portraits
article_types[]:practice guideline
article_types[]:pragmatic clinical trial
article_types[]:publication components
article_types[]:publication formats
article_types[]:publication type category
article_types[]:published erratum
article_types[]:randomized controlled trial
article_types[]:research support, american recovery and reinvestment act
article_types[]:research support, n i h, extramural
article_types[]:research support, n i h, intramural
article_types[]:research support, non u s gov't
article_types[]:research support, u s gov't, non p h s
article_types[]:research support, u s gov't, p h s
article_types[]:research support, u s government
article_types[]:retracted publication
article_types[]:retraction of publication
article_types[]:review
article_types[]:scientific integrity review
article_types[]:study characteristics
article_types[]:support of research
article_types[]:technical report
article_types[]:twin study
article_types[]:validation studies
article_types[]:video audio media
article_types[]:webcasts
from:1808-12-31
to:2017-11-08
q:zika review
```

**Comment by tanteuschi** [comment]
sorting:**most-relevant**
is that the same as sort by: **best match** ?? (that's what I selected in pubmed)

**Comment by sckott** [comment]
hmm, looks like we have "most relevant" and "most recent"  options, but not "best match" (seems like it should be the same as most relevant, but I guess not?)

**Comment by chreman** [comment]
Per reply we have received from PubMed:
> The e-utilities API is retrieving data from the legacy PubMed database. The new PubMed is built with updated technology. Since they are two separate systems, counts will not always match up. Indexing is done at different times for each system, so additions, deletions (e.g., removing duplicates), or updates to records aren't taking effect at the same time in both places. Additionally, there are some changes in search syntax and search translations for the new PubMed that may affect the number of search results.

Since our backend currently relies on the e-utilities API we cannot fix the issue on our side.
