### ISSUE TITLE
Open articles in new tab from the list view

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#176]
It would be nice if it would be possible to open articles in a new tab while viewing the list. I.e., while viewing the list of articles I would like to either click with the middle mouse button (or ctrl + left click) on the titles of articles to open new tabs in my browser

**Comment by pkraker** [comment]
Please clarify: do you mean the PDF or the landing page? You can already open the landing page in a new tab, when you click on the HTML link with the middle mouse button/ctrl+left-click.

**Comment by Bubblbu** [comment]
Ah, I see!

Was trying to achieve "middle mouse button on HTML link" with the article titles. Seemed more intuitive to me in that situation and didn't think of the outlinks

**Comment by tanteuschi** [comment]
this is intended behaviour and will not change in the future.
