### ISSUE TITLE
List view doesn't show article details after deselecting and selecting again

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#177]
Steps to reproduce:

1. Click on article (both in the map and list)
2. Deselect (click on empty space in bubble)
3. Click on title of previously selected article
4. Item only highlighted in map. List view doesn't update

**Comment by pkraker** [comment]
Thanks, I reproduced this bug, but only if I clicked on an article in the list in the zoomed out state in step 1.

**Comment by tanteuschi** [comment]
This works now I checked both your examples @pkraker and @Bubblbu
