### ISSUE TITLE
Advanced search queries fail in BASE

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#198]
As indicated in #179 I was looking into some advanced search queries for BASE that were failing.

Certain advanced queries are failing with BASE. E.g., OR'ing two literal expressions:

`("open science" "open data")` - which is "open science" OR "open data" has [29,788 hits in BASE](https://www.base-search.net/Search/Results?lookfor=%28%22open+science%22+%22open+data%22%29&type=all&oaboost=1&ling=1&name=&newsearch=1&refid=dcbasen) but fails on our end. The linked BASE results page in the error message is: https://base-search.net/Search/Results?refid=okmaps&type0[]=all&lookfor0[]=(

I am not sure where and what is failing exactly as `"open science" "open data"` (which is the two terms with an AND operator) and `(open science)` [open OR science] are seemingly working.

**Comment by pkraker** [comment]
Advanced queries are now possible! You should be able to enter any query that is possible on BASE. The only difference is that we are using the query syntax of the HTTP API (see page 13, point 4 of [this document](https://www.base-search.net/about/download/base_interface.pdf)). This syntax is slightly different; the example that you provided would be interpreted as "open science" AND "open data". To achieve the result you are looking for, simply use "open science" OR "open data".
