### ISSUE TITLE
Endless PubMed search

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#225]
As reported by our user Lena K. via e-mail and as encountered in various offline trainings, there are conditions where the PubMed search results in an endless waiting screen. Maximum waiting time witnessed: 1 hour (on MacOS version 10.13.4, both with Safari 11 and Firefox 59). 

The reason for this is not clear at the moment, but my best guess is that the PubMed API does not send responses any more when a certain amount of requests is sent. It does not report a timeout or an error either, which results in the endless loop. If this assumption is confirmed, we need to set a sensible timeout on our side.

**Comment by chreman** [comment]
The error can be reproduced and fails with `Error in entrez_check(response): HTTP failure: 502, bad gateway. This error code is often returned when trying to download many records in a single request.  Try using web history as described in the rentrez tutorial`.
It currently logs an error on our backend, but does not terminate the query and forward to an error page like when BASE fails.

**Comment by pkraker** [comment]
We introduced a meaningful timeout on the website search, therefore endless searches should not be an issue any more. The original problem still persists and is discussed in #257.
