### ISSUE TITLE
Change "Keywords:" to "Keywords: n/a"

### ISSUE THREAD

**Issue by tanteuschi** [OpenKnowledgeMaps/Headstart#255]
![keywords-empty](https://user-images.githubusercontent.com/19272712/41843229-474b99ea-786d-11e8-85eb-e58809fff66b.png)
Please indicate that there are no keywords as follows: 
Keywords: n/a

**Comment by martinafilipova** [comment]
Hello, I will start working on it :+1:

**Comment by pkraker** [comment]
@martinafilipova Excellent! Please open a PR once you are done.
