### ISSUE TITLE
Clicking on PDF Preview button places cursor

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#256]
Not a biggy, but still caught my eye...

![peek 2018-07-03 15-18](https://user-images.githubusercontent.com/6946077/42247230-af466fee-7ed4-11e8-80d4-0b324adbfdf5.gif)

**Comment by tanteuschi** [comment]
@Bubblbu This seems to be fixed. I wasn't able to reproduce it. Could you let me know if this still occurs and could you also let me know which browser / OS you tested this with?

**Comment by Bubblbu** [comment]
Confirmed, this is fixed.

Browser: Firefox 74.0 (64-bit) for Ubuntu.
OS: Lubuntu 16.04
