### ISSUE TITLE
BASE: It's not possible to mix phrase and keyword search

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#267]
In the BASE integration, one can search for `open access africa` and `"open access africa"`, but not for `"open access" africa`. This does work in the PubMed integration, see e.g. [this map](https://openknowledgemaps.org/map/b9030fa7af84b912920839f2ad27e757) for `"heart attack" cell`.

**Comment by Bubblbu** [comment]
I think that BASE does actually support mixed searches, but uses an uncommon (at least I haven't encountered it anywhere else) search syntax. See #198, but I'm also not entirely sure about this. Probably getting in touch with BASE directly would help to resolve this

**Comment by pkraker** [comment]
Fixed by extending the relevant regex to handle phrases, not just keywords.
