### ISSUE TITLE
Jumping between a single paper and all papers in the bubble triggers exception

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#28]
Exception: "uncaught exception: event zoom inappropriate in current state enlarged"

Steps to reproduce:
1. Click on bubble
2. Click on a paper title in the list
3. Enter search term
4. Click on the bubble
5. Click on the same paper in the list
6. Click on the bubble again

**Comment by pkraker** [comment]
The exception is gone, but the visualization now zooms out after step 4, which it shouldn't do. It should rather display the filtered list.

**Comment by Bubblbu** [comment]
Interestingly PR #107 changed this insofar, that *sometimes* step 4 leads to the expected behaviour and sometimes still fails :confused:

**Comment by chreman** [comment]
@pkraker can this issue be closed? I could not reproduce the bug with the given steps on a four maps (machine learning & digital education on base & pubmed)

**Comment by pkraker** [comment]
@chreman Thanks for the pointer, I could also not reproduce this bug any more.
