### ISSUE TITLE
Backend: Snapshot testing differences on Windows

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#282]
On Windows, snapshot testing always produces differences, even when the test is performed with the same revision. The affected fields are `area_uri`, `cluster_labels` and `area` (as well as `x` and `y`, which is expected).

One reason for this may be encoding. To even make base_snapshot.R and pubmed_snapshot.R working, one needs to manually convert the files created by `create_snapshots.R` to UTF-8.

Tested with Windows 7 and 10 on R 3.3.x and R 4.4.x.

**Comment by chreman** [comment]
Superseded by other testing workflow improvements.
