### ISSUE TITLE
Split viz-requests into smaller parts

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#31]
Current requests are processed from start till end in one go and cause the known waiting times for users. In order to enhance the user experience we could split a request in:
1. _Get data from PLOS_
   
   Once the data is retrieved from PLOS the list containing the papers can already be displayed.
2. _Calculate the map_ ...
   
   ... while the user explores the papers as a list.

**Comment by pkraker** [comment]
One of the problems with this behaviour would be that the list interacts with the visualization. So when people start to explore the list, then we need to decide what we want to do once the visualization is loaded. Do we (a) put the visualization in the state of the list, or (b) do we reset the list. From my point of view, both behaviours would most likely break the user experience to some extent. I am not saying that it is impossible to do, but we also need to be sure that it is worth the time that we gain by invoking such a behaviour.

**Comment by Bubblbu** [comment]
That's true... Resetting the list/starting the viz in a certain state both seem like half-baken solutions.

Anoter (also far from perfect) approach could be to minimize interaction in the beginning and restrict interactions to viewing items.
Maybe we could try to use a visual indicator when the list is finally interactive and explorable. (small pop-up message; small loading icon; greyed out and then in color)
