### ISSUE TITLE
BASE: search for query with documents fails

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#372]
When searching for `börner katy` with the BASE integration, the search fails with "Sorry! We could not create a map for your search term. Most likely there were not enough results." However, the [same search on BASE](https://base-search.net/Search/Results?refid=okmaps&type0[]=all&lookfor0[]=b%C3%B6rner%20katy&type0[]=tit&lookfor0[]=&type0[]=aut&lookfor0[]=&type0[]=subj&lookfor0[]=&type0[]=url&lookfor0[]=&offset=10&ling=0&type0[]=country&lookfor0[]=&daterange=year&yearfrom=1665&yearto=2019&type1[]=doctype&lookfor1[]=121&allrights=all&type2[]=rights&lookfor2[]=CC-*&lookfor2[]=CC-BY&lookfor2[]=CC-BY-SA&lookfor2[]=CC-BY-ND&lookfor2[]=CC-BY-NC&lookfor2[]=CC-BY-NC-SA&lookfor2[]=CC-BY-NC-ND&lookfor2[]=PD&lookfor2[]=CC0&lookfor2[]=PDM&type3[]=access&lookfor3[]=1&lookfor3[]=0&lookfor3[]=2&name=&join=AND&bool0[]=AND&bool1[]=OR&bool2[]=OR&bool3[]=OR&newsearch=1) has 31 hits.

**Comment by tanteuschi** [comment]
This works now. Here is the Knowledge Map for **börner katy** https://openknowledgemaps.org/map/6c3b6be7c20abf097a3e77a446033692
