### ISSUE TITLE
Use PCA to make map layout consistent

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#46]
Currently the maps are not reproducible in the sense that the same papers as input will create differently rotated maps. By using PCA after NMDA, which would align the first NMDA axis with the direction of maximum variance.

**Comment by Bubblbu** [comment]
@chreman your thoughts on that?

**Comment by pkraker** [comment]
It seems that there are other MDS packages that have implemented this: [MDSrotate](https://rdrr.io/rforge/vegan/man/MDSrotate.html)

**Comment by tanteuschi** [comment]
Consistent map layout was implemented by @chreman
Thank you :-)
