### ISSUE TITLE
Force layout server side vs client side

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#47]
Currently we are using the D3 implementation of Force Layout on client side. 

Not sure if there is a noticeable difference in performance if we run force layout on the server in R for  ~100 nodes and deliver the final map. But I guess that the performance should at least improve for weaker devices?

But most importantly the user would no longer have the waiting phase until the layout is finished. This would also solve #31. As the map is ready to go from the start we no longer need to worry about the synchronization between paper list and map.

**Comment by pkraker** [comment]
Closing this for now as the speed of the force-directed layout on the client has been considerably improved.
