### ISSUE TITLE
DOAJ: Author list is always one author short

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#87]
The last author is missing from both the list and the paper in the DOAJ integration.

**Comment by sckott** [comment]
any eg's on hand?

**Comment by pkraker** [comment]
I have concluded now that this is a frontend issue, which is also present in the Pubmed integration. See e.g. http://openknowledgemaps.org/vis.php?id=ca6464fafff803d65463e2c4d2636632&query=frog&service=doaj - the very first paper does have an auhtor, but it's not listed.

**Comment by sckott** [comment]
right, looks like author is there in results

```r
x = jaod_article_search("doi:10.5958/j.2319-5886.2.2.016")
x$results$bibjson.author
#> [[1]]
#>                                                         name
#> 1 Lakhavat Sudhakar, Naveen Kumar T, Tadvi NA, Venkata Rao Y
```
