### ISSUE TITLE
TimeLineView: Link lines could be optimized

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#90]
In the TimeLineView, the link lines are not very well aligned to the bubbles. See below

![link_lines](https://cloud.githubusercontent.com/assets/6399997/21896697/8eee9f94-d8e7-11e6-9547-7e97510f327b.png)

**Comment by tanteuschi** [comment]
We are not going to improve this mode. We started working on a better solution to analyze topics over time: streamgraph.
