### ISSUE TITLE
"esc" to exit pdf preview?

### ISSUE THREAD

**Issue by sckott** [OpenKnowledgeMaps/Headstart#93]
when looking at a pdf preview would it be easy enough to allow hitting `esc` to exit the preview?

e.g., when here 

<img width="1265" alt="screen shot 2017-01-27 at 10 14 16 am" src="https://cloud.githubusercontent.com/assets/577668/22382175/63ce951a-e479-11e6-8327-f83ba382d58a.png">

**Comment by pkraker** [comment]
Good idea, I'll have a look whether the modals we're using support that.

**Comment by Bubblbu** [comment]
fd6fb4da9114aecf166399350201907439bba861
