### ISSUE TITLE
DOAJ integration: "empty" labels

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#95]
In the DOAJ integration, some of the labels seem to be empty. Closer inspection shows that they consist of unicode characters which are represented in the form of `<U+XXXX>`. The examples are taken from [this map on archaeology](http://openknowledgemaps.org/vis.php?id=f207a104e4aabe18ed4f84413405a91e&query=archaeology&service=doaj).

![label_error_1](https://cloud.githubusercontent.com/assets/6399997/22404314/8ecbf594-e62e-11e6-9108-ee72a577706c.png)

![label_error_2](https://cloud.githubusercontent.com/assets/6399997/22404317/93a99d50-e62e-11e6-8782-ee68993a6af9.png)

**Comment by sckott** [comment]
@pkraker  its possible that's on the R end, but not sure. Can you tell where in the pipeline the problem may be?

**Comment by chreman** [comment]
I'll hopefully can add some info once I had a look at the raw data from the evaluation.

**Comment by pkraker** [comment]
@sckott Not sure where the problem lies. Let's wait for @chreman's analysis.

**Comment by sckott** [comment]
ok

**Comment by pkraker** [comment]
Coincidentally, I've had a similar problem in another project today. In this case, it was the API's fault. I ended up replacing all instances of `<U+0000>` with `&#x0000;`.

**Comment by chreman** [comment]
so, if decoded it states с и м п о з и у м Р у м ъ н и я М е ж д у н а р о д е н (Symposyium Rymniya Mezhdunaroden, something about an international symposium on sth.), 
appearing in the title of a search result. the search result seems valid otherwise.

**Comment by pkraker** [comment]
It could very well be the PHP service's fault, I'll take a look. Most likely, some encoding conversion in the keyword labelling fails. All the more reason to consider moving the labelling procedure to R.
